export const SET_CAMERA_TYPE_LIST = "@CAMERA_TYPE/SET_CAMERA_TYPE_LIST";
export const OPEN_CAMERA_TYPE_DIALOG = "@CAMERA_TYPE/OPEN_CAMERA_TYPE_DIALOG";
export const CLOSE_CAMERA_TYPE_DIALOG = "@CAMERA_TYPE/CLOSE_CAMERA_TYPE_DIALOG";
