export const ADD_CAMERA_TYPE = "@CAMERA_TYPE/ADD_CAMERA_TYPE";
export const EDIT_CAMERA_TYPE = "@CAMERA_TYPE/EDIT_CAMERA_TYPE";
export const OPEN_CAMERA_TYPE_DIALOG = "@CAMERA_TYPE/OPEN_CAMERA_TYPE_DIALOG";
export const CLOSE_CAMERA_TYPE_DIALOG = "@CAMERA_TYPE/CLOSE_CAMERA_TYPE_DIALOG";
export const DELETE_CAMERA_TYPE = "@CAMERA_TYPE/DELETE_CAMERA_TYPE";
