export const ADD_CAMERA = "@CAMERA/ADD_CAMERA";
export const EDIT_CAMERA = "@CAMERA/EDIT_CAMERA";
export const OPEN_CAMERA_DIALOG = "@CAMERA/OPEN_CAMERA_DIALOG";
export const CLOSE_CAMERA_DIALOG = "@CAMERA/CLOSE_CAMERA_DIALOG";
export const DELETE_CAMERA = "@CAMERA/DELETE_CAMERA";
